### PR TITLE
Fix incorect name field for password confirmation for installation

### LINKED ISSUE #48: Ask for password twice when trying to update it.

### PR DESCRIPTION
**Pull request by FoxiesCuties**
Due to the " Fix #48" an password verification has added.

He use "confirm_password"  instead of "password_confirmation"

My fix rename the data label from "password_confirmation" to
"confirm_password"

### CODE REVIEW

File: app/Controller/InstallersController.php [hunk 1]
```diff
@@ -107,7 +107,7 @@ public function index() {
             $this->request->data['Setting']['enable_auto_conv'] = $libavtools;
 
 
-            if($this->request->data['User']['password'] != $this->request->data['User']['password_confirmation']){
+            if($this->request->data['User']['password'] != $this->request->data['User']['confirm_password']){
```
Comment (FoxiesCuties) [inline app/Controller/InstallersController.php]: Adapt data label for Fix #48

File: app/View/Installers/index.ctp [hunk 2]
```diff
@@ -97,7 +97,7 @@
         <?php
         echo $this->Form->input('User.email', array('placeholder' => 'john.doe@sonerezh.bzh'));
         echo $this->Form->input('User.password', array('placeholder' => __('Password'), 'label' => array('text' => __('Password (twice)'), 'class' => 'col-sm-3 control-label')));
-        echo $this->Form->input('User.password_confirmation', array('placeholder' => __('Confirm your password'), 'type' => 'password', 'label' => array('text' => '', 'class' => 'col-sm-3 control-label')));
+        echo $this->Form->input('User.confirm_password', array('placeholder' => __('Confirm your password'), 'type' => 'password', 'label' => array('text' => '', 'class' => 'col-sm-3 control-label')));
```
Comment (FoxiesCuties) [inline app/View/Installers/index.ctp]: Adapt data label for Fix #48

**Comment by lGuillaume124** [comment]
Thanks for your contribution!
